env:
  browser: true
  es2021: true
  node: true
globals: {
  _: 'readonly',
  $: 'readonly'
}
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-prototype-builtins: off
}
